spring:
     mail:
      host: smtp.gmail.com
      port: 587
      username: teamsouthlab@gmail.com
      password: kosta1234
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true